CREATE TABLE IF NOT EXISTS projects (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,

    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    color VARCHAR(20) DEFAULT '#3B82F6',
    cover_image TEXT,
    status INTEGER DEFAULT 1 CHECK (status >= 1 AND status <= 3),

    user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
