CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,

    task TEXT NOT NULL,
    description VARCHAR(1000),
    is_roadmap BOOLEAN DEFAULT FALSE,
    priority INTEGER DEFAULT 5 CHECK (priority >= 0 AND priority <= 5),
    due_days INTEGER DEFAULT 0,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    status INTEGER DEFAULT 1 CHECK (status >= 1 AND status <= 6),

    parent_id INTEGER REFERENCES todos(id) ON UPDATE CASCADE ON DELETE SET NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    roadmap_id INTEGER REFERENCES roadmaps(id) ON UPDATE CASCADE ON DELETE SET NULL,
    notes_id INTEGER REFERENCES notes(id) ON UPDATE CASCADE ON DELETE SET NULL
);