
CREATE TABLE IF NOT EXISTS resources (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,

    type INTEGER DEFAULT 1 CHECK (type >= 1 AND type <= 4),
    misc_id INTEGER DEFAULT 0,
    misc_type INTEGER DEFAULT 1 CHECK (misc_type >= 1 AND misc_type <= 4),
    link VARCHAR(255) NULL,
    todo_id INTEGER NOT NULL REFERENCES todos(id) ON DELETE CASCADE ON UPDATE CASCADE
);
