package constants

const (
	APP_NAME    = "Fintrax"
	APP_VERSION = "0.0.1"
	APP_PORT    = ":80"
)

const (
	STATUS_NOT_STARTED = 1
	STATUS_IN_PROGRESS = 2
	STATUS_ON_HOLD     = 3
	STATUS_CANCELLED   = 4
	STATUS_DELETED     = 5
	STATUS_COMPLETED   = 6
)

const (
	FINANCE_TYPE_INCOME  = 1
	FINANCE_TYPE_EXPENSE = 2
)
