package constants

const (
	APP_NAME    = "Fintrax"
	APP_VERSION = "0.0.1"
	APP_PORT    = ":80"
)

const (
	STATUS_NOT_STARTED = 1
	STATUS_IN_PROGRESS = 2
	STATUS_ON_HOLD     = 3
	STATUS_CANCELLED   = 4
	STATUS_DELETED     = 5
	STATUS_COMPLETED   = 6
)

const (
	FINANCE_TYPE_INCOME  = 1
	FINANCE_TYPE_EXPENSE = 2
)

const (
	RESOURCE_TYPE_LINK  = 1
	RESOURCE_TYPE_AUDIO = 2
	RESOURCE_TYPE_VIDEO = 3
	RESOURCE_TYPE_NOTES = 4
)

const (
	MIN_OTP_LENGTH = 1000
	MAX_OTP_LENGTH = 9999
	MAX_OTP_TIME   = 5 // in minutes
)
